name: android_id
description: A Flutter plugin for getting the Android ID. Only for Android.

repository: https://github.com/fluttercommunity/android_id
issue_tracker: https://github.com/fluttercommunity/android_id/issues

maintainer: Joachim Nohl (@nohli)

version: 0.0.5

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: plus.fluttercommunity.dev.android_id
        pluginClass: AndroidIdPlugin
      ohos:
        package: plus.fluttercommunity.dev.android_id
        pluginClass: AndroidIdPlugin
 
